/* Generated by MyraPad at 10/7/2022 10:23:12 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#endif

namespace WorldGenerator.App.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_buttonGenerate = new TextButton();
			_buttonGenerate.Text = "Generate";
			_buttonGenerate.Width = 100;
			_buttonGenerate.Id = "_buttonGenerate";

			_buttonSave = new TextButton();
			_buttonSave.Text = "Save";
			_buttonSave.Width = 100;
			_buttonSave.Id = "_buttonSave";

			_buttonLoad = new TextButton();
			_buttonLoad.Text = "Load";
			_buttonLoad.Width = 100;
			_buttonLoad.Id = "_buttonLoad";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonGenerate);
			horizontalStackPanel1.Widgets.Add(_buttonSave);
			horizontalStackPanel1.Widgets.Add(_buttonLoad);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "Type:";

			_buttonWrapped = new RadioButton();
			_buttonWrapped.Text = "Wrapped";
			_buttonWrapped.Id = "_buttonWrapped";

			_buttonSpherical = new RadioButton();
			_buttonSpherical.Text = "Spherical";
			_buttonSpherical.Id = "_buttonSpherical";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(label1);
			horizontalStackPanel2.Widgets.Add(_buttonWrapped);
			horizontalStackPanel2.Widgets.Add(_buttonSpherical);

			_panelProperties = new Panel();
			_panelProperties.Id = "_panelProperties";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(_panelProperties);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = verticalStackPanel1;

			_buttonHeightMap = new RadioButton();
			_buttonHeightMap.Text = "Height Map";
			_buttonHeightMap.Id = "_buttonHeightMap";

			_buttonHeatMap = new RadioButton();
			_buttonHeatMap.Text = "Heat Map";
			_buttonHeatMap.Id = "_buttonHeatMap";

			_buttonMoistureMap = new RadioButton();
			_buttonMoistureMap.Text = "Moisture Map";
			_buttonMoistureMap.Id = "_buttonMoistureMap";

			_buttonBiomeMap = new RadioButton();
			_buttonBiomeMap.Text = "Biome Map";
			_buttonBiomeMap.Id = "_buttonBiomeMap";

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 8;
			horizontalStackPanel3.Widgets.Add(_buttonHeightMap);
			horizontalStackPanel3.Widgets.Add(_buttonHeatMap);
			horizontalStackPanel3.Widgets.Add(_buttonMoistureMap);
			horizontalStackPanel3.Widgets.Add(_buttonBiomeMap);

			var horizontalSeparator2 = new HorizontalSeparator();

			_image2DView = new Image();
			_image2DView.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_image2DView.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_image2DView.Id = "_image2DView";

			_panelView = new Panel();
			_panelView.Id = "_panelView";
			_panelView.Widgets.Add(_image2DView);

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel2.Widgets.Add(horizontalStackPanel3);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(_panelView);

			_progressLog = new HorizontalProgressBar();
			_progressLog.Value = 50;
			_progressLog.Height = 20;
			_progressLog.Id = "_progressLog";

			_labelLog = new Label();
			_labelLog.Text = "GetData";
			_labelLog.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelLog.Id = "_labelLog";

			var panel1 = new Panel();
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			panel1.Widgets.Add(_progressLog);
			panel1.Widgets.Add(_labelLog);

			var panel2 = new Panel();
			panel2.Widgets.Add(verticalStackPanel2);
			panel2.Widgets.Add(panel1);

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			_splitPane.Widgets.Add(scrollViewer1);
			_splitPane.Widgets.Add(panel2);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_splitPane);
		}

		
		public TextButton _buttonGenerate;
		public TextButton _buttonSave;
		public TextButton _buttonLoad;
		public RadioButton _buttonWrapped;
		public RadioButton _buttonSpherical;
		public Panel _panelProperties;
		public RadioButton _buttonHeightMap;
		public RadioButton _buttonHeatMap;
		public RadioButton _buttonMoistureMap;
		public RadioButton _buttonBiomeMap;
		public Image _image2DView;
		public Panel _panelView;
		public HorizontalProgressBar _progressLog;
		public Label _labelLog;
		public HorizontalSplitPane _splitPane;
	}
}
