/* Generated by MyraPad at 11/11/2020 4:53:19 AM */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace FantasyMapGenerator.App.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_buttonGenerate = new TextButton();
			_buttonGenerate.Text = "Generate";
			_buttonGenerate.Width = 100;
			_buttonGenerate.Id = "_buttonGenerate";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_buttonGenerate);

			var horizontalSeparator1 = new HorizontalSeparator();

			_panelProperties = new Panel();
			_panelProperties.ClipToBounds = true;
			_panelProperties.Id = "_panelProperties";

			_panelMap = new Panel();
			_panelMap.ClipToBounds = true;
			_panelMap.Id = "_panelMap";

			_panelLog = new Panel();
			_panelLog.Id = "_panelLog";

			var panel1 = new Panel();
			panel1.Widgets.Add(_panelMap);
			panel1.Widgets.Add(_panelLog);

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			_splitPane.Widgets.Add(_panelProperties);
			_splitPane.Widgets.Add(panel1);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_splitPane);
		}

		
		public TextButton _buttonGenerate;
		public Panel _panelProperties;
		public Panel _panelMap;
		public Panel _panelLog;
		public HorizontalSplitPane _splitPane;
	}
}